[project]
name = "external-sentinel"
authors = ["External Sentinel Team"]
description = "Decentralized project tracking and monitoring system"
telemetry = false
requirements = []
[contracts.sentinel-workflow]
path = "contracts/sentinel-workflow.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
